ludus:
  - vm_name: "{{ range_id }}-PRIMARYDC"
    hostname: "PRIMARYDC"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 10
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: false
    domain:
      fqdn: mineral.local
      role: primary-dc
  - vm_name: "{{ range_id }}-CINNABAR"
    hostname: "CINNABAR"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 20
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: false
    domain:
      fqdn: mineral.local
      role: member
  - vm_name: "{{ range_id }}-GRAPHITE"
    hostname: "GRAPHITE"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 50
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: false
    domain:
      fqdn: mineral.local
      role: member
  - vm_name: "{{ range_id }}-SALESDC"
    hostname: "SALESDC"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 110
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: false
    roles:
      - ludus_child_domain
    role_vars:
      parent_domain_name: "mineral.local"
      new_domain_name: "sales"
      parent_ea_user: "mineral.local\\administrator"
      parent_ea_password: "password"
      parent_dc_ip: "10.{{ range_second_octet }}.10.10"
      current_host_ip: "10.{{ range_second_octet }}.10.110"
  - vm_name: "{{ range_id }}-GOLD"
    hostname: "GOLD"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 150
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: false
    roles:
      - ludus_child_domain_join
    role_vars:
      dc_ip: "10.{{ range_second_octet }}.10.110"
      dns_domain_name: "sales.mineral.local"
      domain_admin_user: "administrator@sales.mineral.local"
      domain_admin_password: "password"
  - vm_name: "{{ range_id }}-ENGDC"
    hostname: "ENGDC"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 210
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: false
    role_vars:
      parent_domain_name: "mineral.local"
      new_domain_name: "engineering"
      parent_ea_user: "mineral.local\\administrator"
      parent_ea_password: "password"
      parent_dc_ip: "10.{{ range_second_octet }}.10.10"
      current_host_ip: "10.{{ range_second_octet }}.10.210"
  - vm_name: "{{ range_id }}-STEEL"
    hostname: "STEEL"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 220
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: false
    roles:
      - ludus_child_domain_join
    role_vars:
      dc_ip: "10.{{ range_second_octet }}.10.210"
      dns_domain_name: "engineering.mineral.local"
      domain_admin_user: "administrator@engineering.mineral.local"
      domain_admin_password: "password"
