ludus:
  - vm_name: "{{ range_id }}-PRIMARYDC"
    hostname: "PRIMARYDC"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 10
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-CINNABAR"
    hostname: "CINNABAR"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 20
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-GRAPHITE"
    hostname: "GRAPHITE"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 50
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-SALESDC"
    hostname: "SALESDC"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 110
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-GOLD"
    hostname: "GOLD"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 150
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-ENGDC"
    hostname: "ENGDC"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 210
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: true
  - vm_name: "{{ range_id }}-STEEL"
    hostname: "STEEL"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 220
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: true
